# Файл docker-compose.yml

# Версия docker-compose
version: '3'

# Перечень volume - то, что не меняется после пересборки контейнера
volumes:
  pg_data:
  static:
  media:

# Перечень контейнеров
# Все контейнеры, описанные в docker-compose.yml, будут запущены в сети (Docker network). 
# Эту сеть Docker Compose создаст автоматически, описывать её в конфиге необязательно.
services:
  db:
    # Из какого образа запустить контейнер:
    image: postgres:13.10
    # Файл (или список файлов) с переменными окружения
    env_file: .env
    # Какой volume подключить для этого контейнера
    volumes:
      - pg_data:/var/lib/postgresql/pg_data
  # Имя и описание контейнера с бэкендом
  backend:
    # Из какого Dockerfile собирать образ для этого контейнера:
    build: ./backend/
    env_file: .env
    # Какой volume подключить для этого контейнера
    volumes:
      - static:/backend_static
      - media:/app/media/
    # Какие контейнеры нужно запустить до старта этого контейнера:
    depends_on:
      - db
  # Имя и описание контейнера с Nginx
  gateway:
    # Сбилдить и запустить образ, 
    # описанный в Dockerfile в папке gateway
    build: ./gateway/
    # Ключ ports устанавливает
    # перенаправление всех запросов с порта 8000 хоста
    # на порт 80 контейнера.
    volumes:
      - static:/staticfiles/
      - media:/app/media/
    ports:
      - 8000:80
